import { existsSync, lstatSync, rmSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { enabledTools, folder, type EnvironmentConfig } from "./config.ts";
import { listConnections, mcpServersFor } from "./connections.ts";
import { ensureDir, linkDir, linksTo, listDir, readJson, readText, writeJson, writeText } from "./fsx.ts";
import { parseFrontmatter } from "./frontmatter.ts";
import { toClaudePermissions, type Permissions } from "./permissions.ts";
import { CODEX_HEADER, codexConfig, codexRules, geminiAllowed, opencodeMcp, opencodePermission } from "./aitools.ts";
import { asObj, Ledger, mergeHooks, mergeKeys, withAgentsPointer } from "./coexist.ts";

const CLAUDE_EVENTS: Record<string, string> = {
  "pre-tool": "PreToolUse",
  "post-tool": "PostToolUse",
  "session-start": "SessionStart",
  prompt: "UserPromptSubmit",
  stop: "Stop",
};

interface NexoHook {
  event: string;
  match: string;
  run: string;
}

function claudeHooks(libraryDir: string): Record<string, unknown[]> {
  const hooks: Record<string, unknown[]> = {};
  const dir = join(libraryDir, "hooks");
  for (const file of listDir(dir).filter((f) => f.endsWith(".json"))) {
    const hook = readJson<NexoHook>(join(dir, file));
    const event = CLAUDE_EVENTS[hook.event];
    if (!event) continue;
    const command = hook.run.startsWith("scripts/") ? `node "${join(dir, hook.run)}"` : hook.run;
    const entry: Record<string, unknown> = { hooks: [{ type: "command", command }] };
    // Command patterns are checked by the hook itself; Claude matches on the tool name.
    if (event === "PreToolUse" || event === "PostToolUse") entry.matcher = "Bash";
    (hooks[event] ??= []).push(entry);
  }
  return hooks;
}

/** Nexo tool names (lowercase) → Claude Code's. Unknown names pass through capitalized. */
const CLAUDE_TOOLS: Record<string, string> = {
  read: "Read", write: "Write", edit: "Edit", grep: "Grep", glob: "Glob", bash: "Bash",
  web: "WebFetch", webfetch: "WebFetch", websearch: "WebSearch", todo: "TodoWrite",
};
const GENERATED = "<!-- Generated by nexo from library/agents; edit that file instead. -->";

/** library/agents/*.md as Claude Code subagents (.claude/agents/), with Claude's tool names. */
function writeClaudeAgents(libraryDir: string, targetDir: string): string[] {
  const out = join(targetDir, ".claude", "agents");
  // Remove agents we generated earlier (the library may have dropped one); leave the user's own files alone.
  for (const f of listDir(out)) if (f.endsWith(".md") && readText(join(out, f)).includes(GENERATED)) rmSync(join(out, f));
  const written: string[] = [];
  for (const file of listDir(join(libraryDir, "agents")).filter((f) => f.endsWith(".md"))) {
    const { data, body } = parseFrontmatter(readText(join(libraryDir, "agents", file)));
    const name = String(data.name ?? basename(file, ".md"));
    const tools = (Array.isArray(data.tools) ? data.tools : String(data.tools ?? "").split(","))
      .map((t) => t.trim())
      .filter(Boolean)
      .map((t) => CLAUDE_TOOLS[t.toLowerCase()] ?? t.charAt(0).toUpperCase() + t.slice(1));
    const lines = [`name: ${name}`, `description: ${String(data.description ?? "")}`];
    if (tools.length) lines.push(`tools: ${tools.join(", ")}`);
    if (data.model) lines.push(`model: ${String(data.model)}`);
    writeText(join(out, `${name}.md`), `---\n${lines.join("\n")}\n---\n${GENERATED}\n\n${body.trimStart()}`);
    written.push(`.claude/agents/${name}.md`);
  }
  return written;
}

/**
 * <dot>/skills → library/skills (relative link), so the AI started here (Claude Code: .claude, OpenCode: .opencode)
 * sees the library's skills. A real folder the user made there is left alone.
 */
function linkSkills(libraryDir: string, targetDir: string, dot = ".claude"): boolean {
  const link = join(targetDir, dot, "skills");
  const want = relative(dirname(link), join(libraryDir, "skills"));
  let stat: ReturnType<typeof lstatSync> | null = null;
  try {
    stat = lstatSync(link);
  } catch {
    stat = null;
  }
  if (stat && !stat.isSymbolicLink()) return false;
  if (stat && linksTo(link, want)) return true;
  if (stat) rmSync(link);
  ensureDir(dirname(link));
  linkDir(want, link);
  return true;
}

/**
 * Generates the per-AI files next to an AGENTS.md (the environment root or a project folder):
 * pointers to AGENTS.md, translated permissions, hooks and MCP servers. Returns written paths.
 */
export function generateAdapters(
  root: string,
  config: EnvironmentConfig,
  targetDir: string,
  permissions: Permissions,
): string[] {
  const written: string[] = [];
  const libraryDir = folder(root, config, "library");
  const connections = listConnections(libraryDir);
  // Other frameworks share these files: only what Nexo wrote last time is replaced (coexist.ts).
  const ledger = new Ledger(root, folder(root, config, "state"));
  const readObj = (file: string) => (existsSync(file) ? asObj(readJson<unknown>(file)) : {});

  for (const tool of enabledTools(config)) {
    if (tool === "claude") {
      const md = join(targetDir, ".claude", "CLAUDE.md");
      writeText(md, withAgentsPointer(existsSync(md) ? readText(md) : null));
      const settingsFile = join(targetDir, ".claude", "settings.json");
      const settings = readObj(settingsFile);
      const hooks = mergeHooks(settings.hooks, claudeHooks(libraryDir), ledger.get(settingsFile)?.items);
      // Permissions come from permissions.json alone: a framework never widens them.
      writeJson(settingsFile, { ...settings, permissions: toClaudePermissions(permissions, root), hooks: hooks.value });
      ledger.set(settingsFile, { items: hooks.items });
      const mcpFile = join(targetDir, ".mcp.json");
      const servers = mergeKeys(readObj(mcpFile).mcpServers, mcpServersFor(connections, "claude"), ledger.get(mcpFile)?.keys?.mcpServers);
      writeJson(mcpFile, { ...readObj(mcpFile), mcpServers: servers.value });
      ledger.set(mcpFile, { keys: { mcpServers: servers.keys } });
      written.push(".claude/CLAUDE.md", ".claude/settings.json", ".mcp.json");
      if (linkSkills(libraryDir, targetDir)) written.push(".claude/skills");
      written.push(...writeClaudeAgents(libraryDir, targetDir));
    } else if (tool === "gemini") {
      // Settings v2 (nested): context.fileName, tools.allowed; keys the user added under context/tools stay.
      const file = join(targetDir, ".gemini", "settings.json");
      const current = readObj(file);
      delete current.contextFileName; // the v1 key earlier versions of nexo wrote
      const servers = mergeKeys(current.mcpServers, mcpServersFor(connections, "gemini"), ledger.get(file)?.keys?.mcpServers);
      writeJson(file, {
        ...current,
        context: { ...asObj(current.context), fileName: "AGENTS.md" },
        tools: { ...asObj(current.tools), allowed: geminiAllowed(permissions) },
        mcpServers: servers.value,
      });
      ledger.set(file, { keys: { mcpServers: servers.keys } });
      written.push(".gemini/settings.json");
    } else if (tool === "opencode") {
      // OpenCode reads AGENTS.md itself; it gets the permissions, MCP servers, skills and agents.
      const file = join(targetDir, "opencode.json");
      const current = readObj(file);
      const servers = mergeKeys(current.mcp, opencodeMcp(connections), ledger.get(file)?.keys?.mcp);
      writeJson(file, { ...current, $schema: "https://opencode.ai/config.json", permission: opencodePermission(permissions, root), mcp: servers.value });
      ledger.set(file, { keys: { mcp: servers.keys } });
      written.push("opencode.json");
      if (linkSkills(libraryDir, targetDir, ".opencode")) written.push(".opencode/skills");
      written.push(...writeOpencodeAgents(libraryDir, targetDir));
    } else if (tool === "codex") {
      // Codex reads AGENTS.md itself; it gets its config (approvals, MCP) and command rules. A config.toml the user
      // wrote there is never overwritten.
      const config = join(targetDir, ".codex", "config.toml");
      if (!existsSync(config) || readText(config).startsWith(CODEX_HEADER)) {
        writeText(config, codexConfig(permissions, connections));
        written.push(".codex/config.toml");
      }
      writeText(join(targetDir, ".codex", "rules", "nexo.rules"), codexRules(permissions).text);
      written.push(".codex/rules/nexo.rules");
    }
  }
  ledger.save();
  return written;
}

/** library/agents/*.md as OpenCode subagents (.opencode/agents/); the user's own files there are left alone. */
function writeOpencodeAgents(libraryDir: string, targetDir: string): string[] {
  const out = join(targetDir, ".opencode", "agents");
  for (const f of listDir(out)) if (f.endsWith(".md") && readText(join(out, f)).includes(GENERATED)) rmSync(join(out, f));
  const written: string[] = [];
  for (const file of listDir(join(libraryDir, "agents")).filter((f) => f.endsWith(".md"))) {
    const { data, body } = parseFrontmatter(readText(join(libraryDir, "agents", file)));
    const name = String(data.name ?? basename(file, ".md"));
    // OpenCode names models as provider/model; Nexo's "haiku"/"sonnet" are not, so the session's model is used.
    writeText(join(out, `${name}.md`), `---\ndescription: ${String(data.description ?? "")}\nmode: subagent\n---\n${GENERATED}\n\n${body.trimStart()}`);
    written.push(`.opencode/agents/${name}.md`);
  }
  return written;
}
