import { existsSync, lstatSync, rmSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { enabledTools, folder, type EnvironmentConfig } from "./config.ts";
import { listConnections, mcpServersFor } from "./connections.ts";
import { ensureDir, isDir, linkDir, linksTo, listDir, readJson, readText, writeJson, writeText } from "./fsx.ts";
import { parseFrontmatter } from "./frontmatter.ts";
import { toClaudePermissions, type Permissions } from "./permissions.ts";
import { CODEX_HEADER, codexConfig, codexRules, geminiAllowed, opencodeMcp, opencodePermission } from "./aitools.ts";
import { asObj, Ledger, mergeHooks, mergeKeys, withAgentsPointer } from "./coexist.ts";
import { defaultFramework, FRAMEWORK_MARKER, loadFrameworks, projectIdOf, resolveContributions, type Named, type Resolved } from "./frameworks.ts";

const CLAUDE_EVENTS: Record<string, string> = {
  "pre-tool": "PreToolUse",
  "post-tool": "PostToolUse",
  "session-start": "SessionStart",
  prompt: "UserPromptSubmit",
  stop: "Stop",
};

interface NexoHook {
  event: string;
  match: string;
  run: string;
}

function claudeHooks(libraryDir: string, fromFrameworks: Record<string, unknown[]>): Record<string, unknown[]> {
  const hooks: Record<string, unknown[]> = {};
  const dir = join(libraryDir, "hooks");
  for (const file of listDir(dir).filter((f) => f.endsWith(".json"))) {
    const hook = readJson<NexoHook>(join(dir, file));
    const event = CLAUDE_EVENTS[hook.event];
    if (!event) continue;
    const command = hook.run.startsWith("scripts/") ? `node "${join(dir, hook.run)}"` : hook.run;
    const entry: Record<string, unknown> = { hooks: [{ type: "command", command }] };
    // Command patterns are checked by the hook itself; Claude matches on the tool name.
    if (event === "PreToolUse" || event === "PostToolUse") entry.matcher = "Bash";
    (hooks[event] ??= []).push(entry);
  }
  // Hooks of frameworks arrive here only once approved (frameworks.ts).
  for (const [event, list] of Object.entries(fromFrameworks)) (hooks[event] ??= []).push(...list);
  return hooks;
}

/** Nexo tool names (lowercase) → Claude Code's. Unknown names pass through capitalized. */
const CLAUDE_TOOLS: Record<string, string> = {
  read: "Read", write: "Write", edit: "Edit", grep: "Grep", glob: "Glob", bash: "Bash",
  web: "WebFetch", webfetch: "WebFetch", websearch: "WebSearch", todo: "TodoWrite",
};
const GENERATED = "<!-- Generated by nexo from library/agents; edit that file instead. -->";
const isGenerated = (text: string) => text.includes(GENERATED) || text.includes(FRAMEWORK_MARKER);

/**
 * Framework agents and commands (markdown with frontmatter) copied into `out` with a marker line after the frontmatter,
 * so the next generation removes them like Nexo's own. A clash-renamed agent also gets its `name:` rewritten.
 */
function writeFrameworkMarkdown(items: Named[], out: string, rename: boolean): string[] {
  const written: string[] = [];
  for (const item of items) {
    let text = readText(item.path);
    const fm = /^---\r?\n[\s\S]*?\r?\n---\r?\n/.exec(text);
    let head = fm ? fm[0] : "";
    if (rename) head = head.replace(/^name:.*$/m, `name: ${item.name}`);
    const marker = `${FRAMEWORK_MARKER}${item.framework} (third-party); edit that file instead. -->\n`;
    text = `${head}${marker}${text.slice(fm ? fm[0].length : 0)}`;
    writeText(join(out, `${item.name}.md`), text);
    written.push(relative(dirname(dirname(out)), join(out, `${item.name}.md`)).replace(/\\/g, "/"));
  }
  return written;
}

/** library/agents/*.md as Claude Code subagents (.claude/agents/), with Claude's tool names. */
function writeClaudeAgents(libraryDir: string, targetDir: string, fromFrameworks: Named[]): string[] {
  const out = join(targetDir, ".claude", "agents");
  // Remove agents we generated earlier (the library may have dropped one); leave the user's own files alone.
  for (const f of listDir(out)) if (f.endsWith(".md") && isGenerated(readText(join(out, f)))) rmSync(join(out, f));
  const written: string[] = [];
  for (const file of listDir(join(libraryDir, "agents")).filter((f) => f.endsWith(".md"))) {
    const { data, body } = parseFrontmatter(readText(join(libraryDir, "agents", file)));
    const name = String(data.name ?? basename(file, ".md"));
    const tools = (Array.isArray(data.tools) ? data.tools : String(data.tools ?? "").split(","))
      .map((t) => t.trim())
      .filter(Boolean)
      .map((t) => CLAUDE_TOOLS[t.toLowerCase()] ?? t.charAt(0).toUpperCase() + t.slice(1));
    const lines = [`name: ${name}`, `description: ${String(data.description ?? "")}`];
    if (tools.length) lines.push(`tools: ${tools.join(", ")}`);
    if (data.model) lines.push(`model: ${String(data.model)}`);
    writeText(join(out, `${name}.md`), `---\n${lines.join("\n")}\n---\n${GENERATED}\n\n${body.trimStart()}`);
    written.push(`.claude/agents/${name}.md`);
  }
  written.push(...writeFrameworkMarkdown(fromFrameworks, out, true));
  return written;
}

/** Framework commands as .claude/commands/*.md; Nexo has none of its own, and the user's files there stay. */
function writeClaudeCommands(targetDir: string, fromFrameworks: Named[]): string[] {
  const out = join(targetDir, ".claude", "commands");
  for (const f of listDir(out)) if (f.endsWith(".md") && readText(join(out, f)).includes(FRAMEWORK_MARKER)) rmSync(join(out, f));
  return writeFrameworkMarkdown(fromFrameworks, out, false);
}

/**
 * <dot>/skills → library/skills (relative link), so the AI started here (Claude Code: .claude, OpenCode: .opencode)
 * sees the library's skills. A real folder the user made there is left alone.
 *
 * Framework skills must not be written into library/skills (that is the user's). When a framework contributes skills,
 * the link points instead at a generated folder, <state>/nexo/skills/<target>/<tool>/, holding one link per library
 * skill and per framework skill (a clash is prefixed with the framework's name). It is rebuilt on every generation,
 * so a skill added to the library shows up after the next `nexo update`; with no framework skills the plain link above
 * is kept and library skills stay live. A real folder the user made is still left alone (framework skills are then not
 * visible there).
 */
function linkSkills(skillsDir: string, targetDir: string, dot = ".claude"): boolean {
  const link = join(targetDir, dot, "skills");
  const want = relative(dirname(link), skillsDir);
  let stat: ReturnType<typeof lstatSync> | null = null;
  try {
    stat = lstatSync(link);
  } catch {
    stat = null;
  }
  if (stat && !stat.isSymbolicLink()) return false;
  if (stat && linksTo(link, want)) return true;
  if (stat) rmSync(link);
  ensureDir(dirname(link));
  linkDir(want, link);
  return true;
}

function skillsSource(root: string, config: EnvironmentConfig, libraryDir: string, targetDir: string, id: string | null, dot: string, fromFrameworks: Named[]): string {
  const library = join(libraryDir, "skills");
  if (!fromFrameworks.length) return library;
  const dir = join(folder(root, config, "state"), "nexo", "skills", (id ?? "root").replace(/[\\/]/g, "__"), dot.replace(/^\./, ""));
  rmSync(dir, { recursive: true, force: true });
  ensureDir(dir);
  for (const name of listDir(library)) if (isDir(join(library, name))) linkDir(join(library, name), join(dir, name));
  for (const skill of fromFrameworks) linkDir(skill.path, join(dir, skill.name));
  return dir;
}

function takenNames(libraryDir: string, connections: { name: string }[]) {
  const agents = listDir(join(libraryDir, "agents")).filter((f) => f.endsWith(".md")).map((f) => String(parseFrontmatter(readText(join(libraryDir, "agents", f))).data.name ?? basename(f, ".md")));
  return { skills: listDir(join(libraryDir, "skills")), agents, commands: [], connections: connections.map((c) => c.name) };
}

/** What the files for terminal AIs get from frameworks: the default method and the enabled tools (same for every target). */
export function frameworkContributions(root: string, config: EnvironmentConfig): Resolved {
  const libraryDir = folder(root, config, "library");
  const { frameworks } = loadFrameworks(root, config);
  return resolveContributions(frameworks, defaultFramework(config), takenNames(libraryDir, listConnections(libraryDir)));
}

/**
 * Generates the per-AI files next to an AGENTS.md (the environment root or a project folder):
 * pointers to AGENTS.md, translated permissions, hooks and MCP servers. Returns written paths.
 */
export function generateAdapters(
  root: string,
  config: EnvironmentConfig,
  targetDir: string,
  permissions: Permissions,
): string[] {
  const written: string[] = [];
  const libraryDir = folder(root, config, "library");
  const fw = frameworkContributions(root, config);
  const id = projectIdOf(root, config, targetDir);
  // Local MCP servers of enabled frameworks go next to the library's connections, for every AI.
  const connections = [...listConnections(libraryDir), ...fw.connections];
  // Other frameworks share these files: only what Nexo wrote last time is replaced (coexist.ts).
  const ledger = new Ledger(root, folder(root, config, "state"));
  const readObj = (file: string) => (existsSync(file) ? asObj(readJson<unknown>(file)) : {});

  for (const tool of enabledTools(config)) {
    if (tool === "claude") {
      const md = join(targetDir, ".claude", "CLAUDE.md");
      // Framework instructions: marked lines after Nexo's pointer; removed again when the framework is disabled.
      const lines = fw.instructions.flatMap((i) => [`<!-- third-party framework: ${i.framework} -->`, `@${relative(dirname(md), i.path).replace(/\\/g, "/")}`]);
      const before = ledger.get(md)?.items?.lines;
      writeText(md, withAgentsPointer(existsSync(md) ? readText(md) : null, "@../AGENTS.md", lines, before));
      ledger.set(md, { items: { lines } });
      const settingsFile = join(targetDir, ".claude", "settings.json");
      const settings = readObj(settingsFile);
      const hooks = mergeHooks(settings.hooks, claudeHooks(libraryDir, fw.hooks), ledger.get(settingsFile)?.items);
      // Permissions come from permissions.json alone: a framework never widens them.
      writeJson(settingsFile, { ...settings, permissions: toClaudePermissions(permissions, root), hooks: hooks.value });
      ledger.set(settingsFile, { items: hooks.items });
      const mcpFile = join(targetDir, ".mcp.json");
      const servers = mergeKeys(readObj(mcpFile).mcpServers, mcpServersFor(connections, "claude"), ledger.get(mcpFile)?.keys?.mcpServers);
      writeJson(mcpFile, { ...readObj(mcpFile), mcpServers: servers.value });
      ledger.set(mcpFile, { keys: { mcpServers: servers.keys } });
      written.push(".claude/CLAUDE.md", ".claude/settings.json", ".mcp.json");
      if (linkSkills(skillsSource(root, config, libraryDir, targetDir, id, ".claude", fw.skills), targetDir)) written.push(".claude/skills");
      written.push(...writeClaudeAgents(libraryDir, targetDir, fw.agents), ...writeClaudeCommands(targetDir, fw.commands));
    } else if (tool === "gemini") {
      // Settings v2 (nested): context.fileName, tools.allowed; keys the user added under context/tools stay.
      const file = join(targetDir, ".gemini", "settings.json");
      const current = readObj(file);
      delete current.contextFileName; // the v1 key earlier versions of nexo wrote
      const servers = mergeKeys(current.mcpServers, mcpServersFor(connections, "gemini"), ledger.get(file)?.keys?.mcpServers);
      writeJson(file, {
        ...current,
        context: { ...asObj(current.context), fileName: "AGENTS.md" },
        tools: { ...asObj(current.tools), allowed: geminiAllowed(permissions) },
        mcpServers: servers.value,
      });
      ledger.set(file, { keys: { mcpServers: servers.keys } });
      written.push(".gemini/settings.json");
    } else if (tool === "opencode") {
      // OpenCode reads AGENTS.md itself; it gets the permissions, MCP servers, skills and agents.
      const file = join(targetDir, "opencode.json");
      const current = readObj(file);
      const servers = mergeKeys(current.mcp, opencodeMcp(connections), ledger.get(file)?.keys?.mcp);
      writeJson(file, { ...current, $schema: "https://opencode.ai/config.json", permission: opencodePermission(permissions, root), mcp: servers.value });
      ledger.set(file, { keys: { mcp: servers.keys } });
      written.push("opencode.json");
      if (linkSkills(skillsSource(root, config, libraryDir, targetDir, id, ".opencode", fw.skills), targetDir, ".opencode")) written.push(".opencode/skills");
      written.push(...writeOpencodeAgents(libraryDir, targetDir));
    } else if (tool === "codex") {
      // Codex reads AGENTS.md itself; it gets its config (approvals, MCP) and command rules. A config.toml the user
      // wrote there is never overwritten.
      const config = join(targetDir, ".codex", "config.toml");
      if (!existsSync(config) || readText(config).startsWith(CODEX_HEADER)) {
        writeText(config, codexConfig(permissions, connections));
        written.push(".codex/config.toml");
      }
      writeText(join(targetDir, ".codex", "rules", "nexo.rules"), codexRules(permissions).text);
      written.push(".codex/rules/nexo.rules");
    }
  }
  ledger.save();
  return written;
}

/** library/agents/*.md as OpenCode subagents (.opencode/agents/); the user's own files there are left alone. */
function writeOpencodeAgents(libraryDir: string, targetDir: string): string[] {
  const out = join(targetDir, ".opencode", "agents");
  for (const f of listDir(out)) if (f.endsWith(".md") && isGenerated(readText(join(out, f)))) rmSync(join(out, f));
  const written: string[] = [];
  for (const file of listDir(join(libraryDir, "agents")).filter((f) => f.endsWith(".md"))) {
    const { data, body } = parseFrontmatter(readText(join(libraryDir, "agents", file)));
    const name = String(data.name ?? basename(file, ".md"));
    // OpenCode names models as provider/model; Nexo's "haiku"/"sonnet" are not, so the session's model is used.
    writeText(join(out, `${name}.md`), `---\ndescription: ${String(data.description ?? "")}\nmode: subagent\n---\n${GENERATED}\n\n${body.trimStart()}`);
    written.push(`.opencode/agents/${name}.md`);
  }
  return written;
}
