import { existsSync, lstatSync, rmSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { enabledTools, folder, type EnvironmentConfig } from "./config.ts";
import { listConnections, mcpServersFor } from "./connections.ts";
import { ensureDir, linkDir, linksTo, listDir, readJson, readText, writeJson, writeText } from "./fsx.ts";
import { parseFrontmatter } from "./frontmatter.ts";
import { toClaudePermissions, type Permissions } from "./permissions.ts";

const CLAUDE_EVENTS: Record<string, string> = {
  "pre-tool": "PreToolUse",
  "post-tool": "PostToolUse",
  "session-start": "SessionStart",
  prompt: "UserPromptSubmit",
  stop: "Stop",
};

interface NexoHook {
  event: string;
  match: string;
  run: string;
}

function claudeHooks(libraryDir: string): Record<string, unknown[]> {
  const hooks: Record<string, unknown[]> = {};
  const dir = join(libraryDir, "hooks");
  for (const file of listDir(dir).filter((f) => f.endsWith(".json"))) {
    const hook = readJson<NexoHook>(join(dir, file));
    const event = CLAUDE_EVENTS[hook.event];
    if (!event) continue;
    const command = hook.run.startsWith("scripts/") ? `node "${join(dir, hook.run)}"` : hook.run;
    const entry: Record<string, unknown> = { hooks: [{ type: "command", command }] };
    // Command patterns are checked by the hook itself; Claude matches on the tool name.
    if (event === "PreToolUse" || event === "PostToolUse") entry.matcher = "Bash";
    (hooks[event] ??= []).push(entry);
  }
  return hooks;
}

/** Nexo tool names (lowercase) → Claude Code's. Unknown names pass through capitalized. */
const CLAUDE_TOOLS: Record<string, string> = {
  read: "Read", write: "Write", edit: "Edit", grep: "Grep", glob: "Glob", bash: "Bash",
  web: "WebFetch", webfetch: "WebFetch", websearch: "WebSearch", todo: "TodoWrite",
};
const GENERATED = "<!-- Generated by nexo from library/agents; edit that file instead. -->";

/** library/agents/*.md as Claude Code subagents (.claude/agents/), with Claude's tool names. */
function writeClaudeAgents(libraryDir: string, targetDir: string): string[] {
  const out = join(targetDir, ".claude", "agents");
  // Remove agents we generated earlier (the library may have dropped one); leave the user's own files alone.
  for (const f of listDir(out)) if (f.endsWith(".md") && readText(join(out, f)).includes(GENERATED)) rmSync(join(out, f));
  const written: string[] = [];
  for (const file of listDir(join(libraryDir, "agents")).filter((f) => f.endsWith(".md"))) {
    const { data, body } = parseFrontmatter(readText(join(libraryDir, "agents", file)));
    const name = String(data.name ?? basename(file, ".md"));
    const tools = (Array.isArray(data.tools) ? data.tools : String(data.tools ?? "").split(","))
      .map((t) => t.trim())
      .filter(Boolean)
      .map((t) => CLAUDE_TOOLS[t.toLowerCase()] ?? t.charAt(0).toUpperCase() + t.slice(1));
    const lines = [`name: ${name}`, `description: ${String(data.description ?? "")}`];
    if (tools.length) lines.push(`tools: ${tools.join(", ")}`);
    if (data.model) lines.push(`model: ${String(data.model)}`);
    writeText(join(out, `${name}.md`), `---\n${lines.join("\n")}\n---\n${GENERATED}\n\n${body.trimStart()}`);
    written.push(`.claude/agents/${name}.md`);
  }
  return written;
}

/**
 * .claude/skills → library/skills (relative link), so Claude Code started here sees the library's skills.
 * A real folder the user made there is left alone.
 */
function linkClaudeSkills(libraryDir: string, targetDir: string): boolean {
  const link = join(targetDir, ".claude", "skills");
  const want = relative(dirname(link), join(libraryDir, "skills"));
  let stat: ReturnType<typeof lstatSync> | null = null;
  try {
    stat = lstatSync(link);
  } catch {
    stat = null;
  }
  if (stat && !stat.isSymbolicLink()) return false;
  if (stat && linksTo(link, want)) return true;
  if (stat) rmSync(link);
  ensureDir(dirname(link));
  linkDir(want, link);
  return true;
}

function mergeJson(path: string, patch: Record<string, unknown>): void {
  const current = existsSync(path) ? readJson<Record<string, unknown>>(path) : {};
  writeJson(path, { ...current, ...patch });
}

/**
 * Generates the per-AI files next to an AGENTS.md (the environment root or a project folder):
 * pointers to AGENTS.md, translated permissions, hooks and MCP servers. Returns written paths.
 */
export function generateAdapters(
  root: string,
  config: EnvironmentConfig,
  targetDir: string,
  permissions: Permissions,
): string[] {
  const written: string[] = [];
  const libraryDir = folder(root, config, "library");
  const connections = listConnections(libraryDir);

  for (const tool of enabledTools(config)) {
    if (tool === "claude") {
      writeText(join(targetDir, ".claude", "CLAUDE.md"), "@../AGENTS.md");
      mergeJson(join(targetDir, ".claude", "settings.json"), {
        permissions: toClaudePermissions(permissions, root),
        hooks: claudeHooks(libraryDir),
      });
      writeJson(join(targetDir, ".mcp.json"), { mcpServers: mcpServersFor(connections, "claude") });
      written.push(".claude/CLAUDE.md", ".claude/settings.json", ".mcp.json");
      if (linkClaudeSkills(libraryDir, targetDir)) written.push(".claude/skills");
      written.push(...writeClaudeAgents(libraryDir, targetDir));
    } else if (tool === "gemini") {
      mergeJson(join(targetDir, ".gemini", "settings.json"), {
        contextFileName: "AGENTS.md",
        mcpServers: mcpServersFor(connections, "gemini"),
      });
      written.push(".gemini/settings.json");
    }
    // codex and opencode read AGENTS.md natively; nothing to generate yet.
  }
  return written;
}
