// The library's permissions and connections in each AI's own format, beyond Claude Code (permissions.ts has
// Claude's): OpenCode (opencode.json), Codex (.codex/config.toml + .codex/rules/*.rules) and Gemini CLI
// (.gemini/settings.json). Formats checked against each tool's docs on 2026-10-07:
//   OpenCode  https://opencode.ai/docs/permissions/ · /docs/mcp-servers/ · /docs/config/
//   Codex     https://learn.chatgpt.com/docs/extend/mcp · /docs/agent-configuration/rules
//   Gemini    https://geminicli.com/docs/reference/configuration · /docs/reference/policy-engine/
// What a tool cannot express is listed by `unenforced` (shown by `nexo doctor`), never silently dropped.
import { join } from "node:path";
import type { Connection } from "./connections.ts";
import { DECISIONS, type Decision, type Permissions } from "./permissions.ts";

const slash = (p: string) => p.replace(/\\/g, "/");

// ── OpenCode ────────────────────────────────────────────────────────────────────────────────────────────────────

/**
 * opencode.json `permission`: `*` gets the default, then allow, ask, deny rules in that order — OpenCode applies the
 * last matching rule, so on a conflict the stricter decision wins, as in Nexo. Paths become absolute (Nexo's are
 * relative to the environment root, OpenCode's to the project).
 */
export function opencodePermission(perms: Permissions, root: string): Record<string, Record<string, Decision>> {
  const def = perms.default ?? "ask";
  const block = (patterns: Partial<Record<Decision, string[]>> | undefined, map: (p: string) => string) => {
    const out: Record<string, Decision> = { "*": def };
    for (const d of DECISIONS) for (const p of patterns?.[d] ?? []) {
      const key = map(p);
      delete out[key]; // re-insert so the stricter decision comes later
      out[key] = d;
    }
    return out;
  };
  const path = (glob: string) => slash(join(root, glob));
  return { bash: block(perms.commands, (p) => p), read: block(perms.files?.read, path), edit: block(perms.files?.edit, path) };
}

/** opencode.json `mcp`: local servers as a command array. */
export function opencodeMcp(connections: Connection[]): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const c of connections) {
    if (c.type !== "mcp" || !c.command || !c.tools.includes("opencode")) continue;
    out[c.name] = { type: "local", command: [c.command, ...(c.args ?? [])], environment: c.env ?? {}, enabled: true };
  }
  return out;
}

// ── Codex ───────────────────────────────────────────────────────────────────────────────────────────────────────

const CODEX_DECISION: Record<Decision, string> = { allow: "allow", ask: "prompt", deny: "forbidden" };

/**
 * A Nexo command pattern as Codex's `prefix_rule` tokens. Codex matches whole arguments, so "npm run test*" (a partial
 * last word) cannot be said exactly: for deny/ask it widens to "npm run" (stricter is safe), for allow it is skipped
 * (wider would grant more than the user allowed). Null when skipped.
 */
export function codexPrefix(pattern: string, decision: Decision): string[] | null {
  const trimmed = pattern.trim();
  const star = trimmed.endsWith("*");
  const body = star ? trimmed.slice(0, -1) : trimmed;
  const partial = star && !/\s$/.test(body) && body.length > 0; // "test*" glued to a word
  const tokens = body.trim().split(/\s+/).filter(Boolean);
  if (tokens.some((t) => /[*?]/.test(t))) return null; // a wildcard inside: not a prefix
  if (partial) {
    if (decision === "allow") return null;
    tokens.pop();
  }
  return tokens.length ? tokens : null;
}

const starlark = (s: string) => JSON.stringify(s);

/** `.codex/rules/nexo.rules`: one prefix_rule per command pattern Codex can express. */
export function codexRules(perms: Permissions): { text: string; skipped: string[] } {
  const lines = ["# Generated by nexo from library/permissions.json (and the project's); edit those instead.", ""];
  const skipped: string[] = [];
  for (const d of DECISIONS) {
    for (const p of perms.commands?.[d] ?? []) {
      const tokens = codexPrefix(p, d);
      if (!tokens) {
        skipped.push(`commands ${d} "${p}"`);
        continue;
      }
      lines.push(`prefix_rule(pattern = [${tokens.map(starlark).join(", ")}], decision = ${starlark(CODEX_DECISION[d])}, justification = ${starlark(`nexo: ${d} ${p}`)})`);
    }
  }
  return { text: `${lines.join("\n")}\n`, skipped };
}

function tomlValue(v: unknown): string {
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "boolean" || typeof v === "number") return String(v);
  if (Array.isArray(v)) return `[${v.map(tomlValue).join(", ")}]`;
  if (v && typeof v === "object") return `{ ${Object.entries(v).map(([k, x]) => `${tomlKey(k)} = ${tomlValue(x)}`).join(", ")} }`;
  return '""';
}
const tomlKey = (k: string) => (/^[A-Za-z0-9_-]+$/.test(k) ? k : JSON.stringify(k));

export const CODEX_HEADER = "# Generated by nexo from library/ (permissions, connections); edit those instead.";

/**
 * `.codex/config.toml` for a project: how often to ask (from the default decision — never "never": a Nexo default of
 * allow still asks Codex to request approval for what its sandbox blocks) and the MCP servers.
 */
export function codexConfig(perms: Permissions, connections: Connection[]): string {
  const approval = (perms.default ?? "ask") === "deny" ? "untrusted" : "on-request";
  const lines = [CODEX_HEADER, `approval_policy = ${tomlValue(approval)}`, `sandbox_mode = "workspace-write"`];
  for (const c of connections) {
    if (c.type !== "mcp" || !c.command || !c.tools.includes("codex")) continue;
    lines.push("", `[mcp_servers.${tomlKey(c.name)}]`, `command = ${tomlValue(c.command)}`, `args = ${tomlValue(c.args ?? [])}`);
    if (c.env && Object.keys(c.env).length) lines.push(`env = ${tomlValue(c.env)}`);
  }
  return `${lines.join("\n")}\n`;
}

// ── Gemini CLI ──────────────────────────────────────────────────────────────────────────────────────────────────

/** `tools.allowed`: the allowed commands as run_shell_command(<prefix>) (Gemini asks for every other command). */
export function geminiAllowed(perms: Permissions): string[] {
  return [...new Set((perms.commands?.allow ?? []).map((p) => p.trim().replace(/\*$/, "").trim()).filter(Boolean).map((p) => `run_shell_command(${p})`))];
}

// ── What each tool cannot enforce ───────────────────────────────────────────────────────────────────────────────

/** Rules of `perms` the tool's generated files do not enforce, one line each, for `nexo doctor`. */
export function unenforced(tool: string, perms: Permissions): string[] {
  const out: string[] = [];
  const has = (d: Decision, area: "read" | "edit") => (perms.files?.[area]?.[d] ?? []).length > 0;
  if (tool === "codex") {
    out.push(...codexRules(perms).skipped.map((r) => `${r} (Codex matches whole words)`));
    if (has("deny", "read") || has("deny", "edit") || has("ask", "edit")) out.push("file rules (Codex has no per-path rules; its workspace-write sandbox applies)");
    out.push("project rules apply only once you trust the project in Codex");
  }
  if (tool === "gemini") {
    if ((perms.commands?.deny ?? []).length) out.push("command deny rules (Gemini's project policies are disabled upstream; it asks before every command not allowed)");
    if (has("deny", "read") || has("deny", "edit")) out.push("file deny rules (no per-path rules in Gemini's project settings)");
    for (const p of perms.commands?.allow ?? []) if (/\*./.test(p.trim().replace(/\*$/, ""))) out.push(`commands allow "${p}" (Gemini matches a prefix only)`);
  }
  if (tool === "opencode" && Object.keys(perms.connections ?? {}).length) out.push("connection decisions (OpenCode has no per-connection approval)");
  return out;
}
