// Third-party agent frameworks (a company's npm package, a community orchestrator, ...) managed from frameworks/.
// Each lives in frameworks/<name>/ with a framework.json that says where it came from, who manages it, whether it is
// available (enabled) and what it contributes. Like the AI providers: a framework is configured once for the
// environment, chosen per tab in agent-os, and one of the methods can be the environment default (config.framework). Nothing here writes outside frameworks/: generateAdapters (adapters.ts) reads the
// resolved contributions and puts them next to Nexo's own, through the merge rules of coexist.ts.
//
// Rules that hold for every framework: it never touches permissions.json; its hooks stay off until approved
// (`nexo framework enable <name> --hooks`); npm installs run with --ignore-scripts at an exact version; a `path:`
// framework is only referenced (managed: external) and never copied, modified or updated.
import { existsSync } from "node:fs";
import { isAbsolute, join, relative, resolve } from "node:path";
import { folder, type EnvironmentConfig } from "./config.ts";
import { asObj } from "./coexist.ts";
import type { Connection } from "./connections.ts";
import { isDir, listDir, readJson, readText, writeJson } from "./fsx.ts";
import { expandHome } from "./paths.ts";
import { parseFrontmatter } from "./frontmatter.ts";

export interface Contributes {
  /** Skill folders (each holds SKILL.md), relative to the framework's content root. */
  skills: string[];
  /** Subagent / command markdown files, relative to the content root. */
  agents: string[];
  commands: string[];
  /** Claude Code hooks by event; wired only once `hooksApproved`. */
  hooks: Record<string, unknown[]>;
  /** Local MCP servers (`command` + `args` + `env`); `${CLAUDE_PLUGIN_ROOT}` means the content root. */
  mcpServers: Record<string, unknown>;
  /** Markdown files included from CLAUDE.md after Nexo's AGENTS.md. */
  instructions: string[];
}

export interface FrameworkManifest {
  name: string;
  /** `npm:<pkg>@<exact version>` or `path:<absolute dir>`. */
  source: string;
  version: string;
  license: string;
  /** `nexo`: Nexo installed it and may update it. `external`: someone else manages it; Nexo only references it. */
  managed: "nexo" | "external";
  /**
   * `method`: a way of working the user picks per tab (instructions, agents, commands, skills). `tool`: only adds MCP
   * servers / hooks, always on while enabled and never picked.
   */
  kind: Kind;
  /** Available to pick (methods) / active (tools). Adding a framework does not enable it. */
  enabled: boolean;
  hooksApproved: boolean;
  /** The folder with the framework's files: relative to frameworks/<name>/ (npm) or absolute (path). */
  root: string;
  contributes: Contributes;
}

export type Kind = "method" | "tool";

export interface Framework extends FrameworkManifest {
  /** frameworks/<name>/ */
  dir: string;
  /** Absolute content root. */
  contentRoot: string;
}

export type Run = (cmd: string, args: string[], cwd: string) => void;

const NAME = /^[a-z0-9][a-z0-9._-]*$/;
const EXACT = /^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$/;
export const FRAMEWORK_MARKER = "<!-- Generated by nexo from framework ";

export const emptyContributes = (): Contributes => ({ skills: [], agents: [], commands: [], hooks: {}, mcpServers: {}, instructions: [] });

export function frameworksDir(root: string, config: EnvironmentConfig): string {
  return folder(root, config, "frameworks");
}

const strings = (v: unknown): string[] => (Array.isArray(v) ? v.filter((x): x is string => typeof x === "string") : []);
/**
 * Paths a framework lists for its files: relative and inside its own folder only. A package's framework.json could
 * otherwise name `../../.ssh/id_rsa` as "instructions" and have Nexo point every AI at it.
 */
const inside = (v: unknown): string[] =>
  strings(v).filter((p) => p.trim() !== "" && !isAbsolute(p) && !/^[A-Za-z]:/.test(p) && !p.split(/[\\/]/).includes(".."));

/** Instructions, agents, commands or skills make a method; MCP servers and hooks alone make a tool. */
export function kindOf(contributes: Contributes, declared?: unknown): Kind {
  if (declared === "method" || declared === "tool") return declared;
  const c = contributes;
  return c.instructions.length || c.agents.length || c.commands.length || c.skills.length ? "method" : "tool";
}

function normalize(raw: Record<string, unknown>, dir: string): Framework {
  const c = asObj(raw.contributes);
  const rootDir = String(raw.root ?? ".");
  const hooks: Record<string, unknown[]> = {};
  for (const [event, list] of Object.entries(asObj(c.hooks))) if (Array.isArray(list)) hooks[event] = list;
  const contributes: Contributes = { skills: inside(c.skills), agents: inside(c.agents), commands: inside(c.commands), hooks, mcpServers: asObj(c.mcpServers), instructions: inside(c.instructions) };
  return {
    name: String(raw.name ?? ""),
    source: String(raw.source ?? ""),
    version: String(raw.version ?? "unknown"),
    license: String(raw.license ?? "unknown"),
    managed: raw.managed === "nexo" ? "nexo" : "external",
    kind: kindOf(contributes, raw.kind),
    enabled: raw.enabled === true || asObj(raw.enabled).global === true, // the object form is what earlier builds wrote
    hooksApproved: raw.hooksApproved === true,
    root: rootDir,
    contributes,
    dir,
    contentRoot: isAbsolute(rootDir) ? rootDir : resolve(dir, rootDir),
  };
}

/** Every framework in frameworks/, plus the folders whose framework.json cannot be read. */
export function loadFrameworks(root: string, config: EnvironmentConfig): { frameworks: Framework[]; broken: string[] } {
  const base = frameworksDir(root, config);
  const frameworks: Framework[] = [];
  const broken: string[] = [];
  for (const entry of listDir(base)) {
    const dir = join(base, entry);
    const file = join(dir, "framework.json");
    if (!isDir(dir)) continue;
    try {
      const fw = normalize(asObj(readJson<unknown>(file)), dir);
      if (fw.name !== entry) throw new Error("name differs from its folder");
      frameworks.push(fw);
    } catch {
      broken.push(entry);
    }
  }
  return { frameworks, broken };
}

export function saveManifest(fw: Framework): void {
  const { dir: _dir, contentRoot: _root, ...manifest } = fw;
  writeJson(join(fw.dir, "framework.json"), manifest);
}

export function validateFrameworkName(name: string): void {
  if (!NAME.test(name)) throw new Error(`Invalid framework name "${name}": use lowercase letters, digits, ".", "_" or "-".`);
}

export type ParsedSource = { kind: "npm"; pkg: string; version: string } | { kind: "path"; dir: string };

/**
 * `npm:<pkg>@<exact version>` or `path:<dir>`. Ranges and tags (`latest`, `^1`) are refused: what is installed must be
 * what was reviewed. Release downloads (`github:`) are the extension point for managed frameworks: add a `kind` here
 * and a branch in the installer of commands/framework.ts.
 */
export function parseSource(source: string): ParsedSource {
  if (source.startsWith("npm:")) {
    const spec = source.slice(4);
    const at = spec.lastIndexOf("@");
    const pkg = at > 0 ? spec.slice(0, at) : spec;
    const version = at > 0 ? spec.slice(at + 1) : "";
    if (!/^(@[a-z0-9._-]+\/)?[a-z0-9._-]+$/.test(pkg)) throw new Error(`"${pkg}" is not a valid npm package name.`);
    if (!EXACT.test(version)) throw new Error(`Pin an exact version: npm:${pkg}@1.2.3 (got "${version || "none"}"; ranges and tags like latest are refused).`);
    return { kind: "npm", pkg, version };
  }
  if (source.startsWith("path:")) {
    const dir = resolve(expandHome(source.slice(5)));
    return { kind: "path", dir };
  }
  throw new Error(`Unknown source "${source}". Use npm:<pkg>@<version> or path:<dir>.`);
}

interface PackageJson {
  name?: string;
  version?: string;
  license?: string;
}

/** The package.json (or .claude-plugin/plugin.json) facts of a content root. */
export function packageFacts(contentRoot: string): PackageJson {
  for (const file of [join(contentRoot, "package.json"), join(contentRoot, ".claude-plugin", "plugin.json")]) {
    if (existsSync(file)) {
      try {
        return asObj(readJson<unknown>(file)) as PackageJson;
      } catch {
        // an unreadable file just means no facts
      }
    }
  }
  return {};
}

function mdFiles(contentRoot: string, sub: string): string[] {
  return listDir(join(contentRoot, sub)).filter((f) => f.endsWith(".md")).map((f) => `${sub}/${f}`);
}

function jsonIn(file: string): Record<string, unknown> {
  try {
    return existsSync(file) ? asObj(readJson<unknown>(file)) : {};
  } catch {
    return {};
  }
}

/**
 * What a framework contributes: its own `framework.json` (a `contributes` block at the content root, paths relative to
 * it) when it ships one, otherwise the Claude Code plugin layout: skills/*\/SKILL.md, agents/*.md, commands/*.md,
 * hooks/hooks.json, .mcp.json and a root CLAUDE.md.
 */
export function detectContributions(contentRoot: string): Contributes {
  const own = jsonIn(join(contentRoot, "framework.json")).contributes;
  if (own) return normalize({ contributes: own }, contentRoot).contributes;
  const hooksFile = jsonIn(join(contentRoot, "hooks", "hooks.json"));
  const mcpFile = jsonIn(join(contentRoot, ".mcp.json"));
  const hooks: Record<string, unknown[]> = {};
  for (const [event, list] of Object.entries(asObj(hooksFile.hooks ?? hooksFile))) if (Array.isArray(list)) hooks[event] = list;
  return {
    skills: listDir(join(contentRoot, "skills")).filter((d) => existsSync(join(contentRoot, "skills", d, "SKILL.md"))).map((d) => `skills/${d}`),
    agents: mdFiles(contentRoot, "agents"),
    commands: mdFiles(contentRoot, "commands"),
    hooks,
    mcpServers: asObj(mcpFile.mcpServers ?? mcpFile),
    instructions: existsSync(join(contentRoot, "CLAUDE.md")) ? ["CLAUDE.md"] : [],
  };
}

/** The kind a framework's own framework.json declares (top level `kind`), if any. */
export function declaredKind(contentRoot: string): unknown {
  return jsonIn(join(contentRoot, "framework.json")).kind;
}

/** The environment's default method: `framework` in environment.config.json; missing or "nexo" means Nexo's own. */
export const NEXO_METHOD = "nexo";
export function defaultFramework(config: EnvironmentConfig): string {
  return typeof config.framework === "string" && config.framework ? config.framework : NEXO_METHOD;
}

/** A project id as the user writes it ("shop", "api-ws/web"): the path under projects/. */
export function projectIdOf(root: string, config: EnvironmentConfig, targetDir: string): string | null {
  const rel = relative(folder(root, config, "projects"), targetDir).replace(/\\/g, "/");
  return rel && !rel.startsWith("..") && !isAbsolute(rel) ? rel : null;
}

export interface Named {
  name: string;
  framework: string;
  /** Absolute file or folder in the framework. */
  path: string;
}

export interface Resolved {
  skills: Named[];
  agents: Named[];
  commands: Named[];
  /** Local MCP servers as connections, for every AI. */
  connections: Connection[];
  /** Claude Code hooks by event; empty until the framework's hooks are approved. */
  hooks: Record<string, unknown[]>;
  /** Absolute instruction files. */
  instructions: { framework: string; path: string }[];
  /** Names that clashed (and got the framework's prefix), for doctor. */
  clashes: string[];
  /** Hook events waiting for approval, by framework. */
  pendingHooks: Record<string, number>;
}

const subst = <T>(value: T, contentRoot: string): T =>
  JSON.parse(JSON.stringify(value).split("${CLAUDE_PLUGIN_ROOT}").join(contentRoot.replace(/\\/g, "/"))) as T;

/** Names in the library that framework contributions must not shadow. */
export interface Taken {
  skills: string[];
  agents: string[];
  commands: string[];
  connections: string[];
}

/** Wired into the files generated for terminal AIs: every enabled tool, and the environment's default method. */
export const isWired = (fw: Framework, defaultName: string): boolean => fw.enabled && (fw.kind === "tool" || fw.name === defaultName);

/**
 * The contributions of the frameworks wired for the AIs used in a terminal (see isWired). A name that is already taken (by the library or by an
 * earlier framework) is prefixed `<framework>-`, and reported in `clashes`.
 */
export function resolveContributions(frameworks: Framework[], defaultName: string, taken: Taken): Resolved {
  const out: Resolved = { skills: [], agents: [], commands: [], connections: [], hooks: {}, instructions: [], clashes: [], pendingHooks: {} };
  const used = { skills: new Set(taken.skills), agents: new Set(taken.agents), commands: new Set(taken.commands), connections: new Set(taken.connections) };
  const claim = (kind: keyof typeof used, fw: string, name: string): string => {
    let final = name;
    if (used[kind].has(name)) {
      final = `${fw}-${name}`;
      out.clashes.push(`${kind.replace(/s$/, "")} "${name}" of ${fw} clashes; used as "${final}"`);
    }
    used[kind].add(final);
    return final;
  };
  for (const fw of frameworks.filter((f) => isWired(f, defaultName))) {
    const at = (rel: string) => join(fw.contentRoot, rel);
    for (const rel of fw.contributes.skills) {
      if (isDir(at(rel))) out.skills.push({ framework: fw.name, name: claim("skills", fw.name, rel.split("/").pop()!), path: at(rel) });
    }
    for (const [kind, list] of [["agents", fw.contributes.agents], ["commands", fw.contributes.commands]] as const) {
      for (const rel of list) {
        if (!existsSync(at(rel))) continue;
        const base = rel.split("/").pop()!.replace(/\.md$/, "");
        const name = kind === "agents" ? String(parseFrontmatter(readText(at(rel))).data.name ?? base) : base;
        out[kind].push({ framework: fw.name, name: claim(kind, fw.name, name), path: at(rel) });
      }
    }
    for (const [name, server] of Object.entries(fw.contributes.mcpServers)) {
      const s = asObj(subst(server, fw.contentRoot));
      if (typeof s.command !== "string") continue; // only local servers are wired
      out.connections.push({
        name: claim("connections", fw.name, name),
        description: `from framework ${fw.name}`,
        type: "mcp",
        command: s.command,
        args: strings(s.args),
        env: Object.fromEntries(Object.entries(asObj(s.env)).map(([k, v]) => [k, String(v)])),
        tools: ["claude", "codex", "gemini", "opencode"],
        owner: fw.name,
      });
    }
    const hookCount = Object.values(fw.contributes.hooks).reduce((n, l) => n + l.length, 0);
    if (hookCount && !fw.hooksApproved) out.pendingHooks[fw.name] = hookCount;
    else for (const [event, list] of Object.entries(subst(fw.contributes.hooks, fw.contentRoot))) (out.hooks[event] ??= []).push(...list);
    for (const rel of fw.contributes.instructions) if (existsSync(at(rel))) out.instructions.push({ framework: fw.name, path: at(rel) });
  }
  return out;
}
