import { join } from "node:path";
import { parseFrontmatter } from "./frontmatter.ts";
import { isDir, listDir, readJson, readText, writeJson } from "./fsx.ts";
import { existsSync } from "node:fs";
import { listConnections } from "./connections.ts";

interface Entry {
  name: string;
  description: string;
  owner: string;
  path: string;
}

function mdEntry(libraryDir: string, rel: string, fallbackName: string): Entry {
  const { data } = parseFrontmatter(readText(join(libraryDir, rel)));
  return {
    name: String(data.name ?? fallbackName),
    description: String(data.description ?? ""),
    owner: String(data.owner ?? "user"),
    path: rel,
  };
}

function jsonEntry(libraryDir: string, rel: string, fallbackName: string): Entry {
  const data = readJson<Record<string, unknown>>(join(libraryDir, rel));
  return {
    name: String(data.name ?? fallbackName),
    description: String(data.description ?? ""),
    owner: String(data.owner ?? "user"),
    path: rel,
  };
}

/** Rebuilds library/index.json — the only library file an agent loads up front. */
export function buildLibraryIndex(libraryDir: string): void {
  const dirEntries = (kind: string, file: string) =>
    listDir(join(libraryDir, kind))
      .filter((name) => existsSync(join(libraryDir, kind, name, file)))
      .map((name) => mdEntry(libraryDir, join(kind, name, file), name));
  const fileEntries = (kind: string, ext: string, reader: typeof mdEntry) =>
    listDir(join(libraryDir, kind))
      .filter((f) => f.endsWith(ext) && f !== "index.json")
      .map((f) => reader(libraryDir, join(kind, f), f.slice(0, -ext.length)));

  const memoryIndex = join(libraryDir, "memory", "index.json");
  writeJson(join(libraryDir, "index.json"), {
    $comment: "Generated by nexo. Load this first; open other files only when the task needs them.",
    skills: dirEntries("skills", "SKILL.md"),
    agents: fileEntries("agents", ".md", mdEntry),
    hooks: fileEntries("hooks", ".json", jsonEntry),
    commands: fileEntries("commands", ".json", jsonEntry),
    conventions: dirEntries("conventions", "README.md"),
    dictionary: listDir(join(libraryDir, "dictionary")).filter((f) => !isDir(join(libraryDir, "dictionary", f))),
    connections: listConnections(libraryDir).map((c) => ({ name: c.name, description: c.description, type: c.type, tools: c.tools })),
    memory: {
      index: "memory/index.json",
      entries: existsSync(memoryIndex) ? readJson<unknown[]>(memoryIndex).length : 0,
    },
  });
}
