// Every AI gets the library: permissions, MCP connections, skills and agents in OpenCode's, Codex's and Gemini's own
// files; what a tool cannot express is reported, never dropped silently.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { freshEnv } from "./helpers.ts";
import { update } from "../src/commands/update.ts";
import { codexConfig, codexPrefix, codexRules, CODEX_HEADER, geminiAllowed, opencodeMcp, opencodePermission, unenforced } from "../src/core/aitools.ts";
import type { Connection } from "../src/core/connections.ts";
import type { Permissions } from "../src/core/permissions.ts";

const PERMS: Permissions = {
  default: "ask",
  commands: { allow: ["git status*", "npm run test*"], ask: ["git tag*"], deny: ["git tag -d*", "rm -rf*"] },
  files: { read: { allow: ["**"], deny: ["secrets/**"] }, edit: { allow: ["projects/*/context/**"], deny: ["library/permissions.json"] } },
};
const MCP: Connection[] = [
  { name: "notion", description: "", type: "mcp", command: "npx", args: ["-y", "notion-mcp"], env: { TOKEN_REF: "secrets/notion" }, tools: ["opencode", "codex"] },
  { name: "remote", description: "", type: "remote", tools: ["opencode", "codex"] },
  { name: "claude-only", description: "", type: "mcp", command: "x", tools: ["claude"] },
];

test("OpenCode: default first, stricter decisions last (OpenCode applies the last match), absolute paths", () => {
  const p = opencodePermission(PERMS, "/env");
  assert.deepEqual(Object.entries(p.bash!), [["*", "ask"], ["git status*", "allow"], ["npm run test*", "allow"], ["git tag*", "ask"], ["git tag -d*", "deny"], ["rm -rf*", "deny"]]);
  assert.deepEqual(p.read, { "*": "ask", "/env/**": "allow", "/env/secrets/**": "deny" });
  assert.deepEqual(Object.keys(p.edit!).at(-1), "/env/library/permissions.json");
  const both = opencodePermission({ commands: { allow: ["x*"], deny: ["x*"] } }, "/r");
  assert.equal(both.bash!["x*"], "deny", "a pattern in allow and deny ends as deny");
  assert.deepEqual(opencodeMcp(MCP), { notion: { type: "local", command: ["npx", "-y", "notion-mcp"], environment: { TOKEN_REF: "secrets/notion" }, enabled: true } });
});

test("Codex: whole-word prefixes; a partial last word widens for deny/ask and is skipped for allow", () => {
  assert.deepEqual(codexPrefix("git status*", "allow"), null, "glued star on the last word: allow would widen");
  assert.deepEqual(codexPrefix("git status *", "allow"), ["git", "status"]);
  assert.deepEqual(codexPrefix("npm run test*", "deny"), ["npm", "run"]);
  assert.equal(codexPrefix("npm run test*", "allow"), null);
  assert.deepEqual(codexPrefix("make", "allow"), ["make"]);
  assert.equal(codexPrefix("docker * rm", "deny"), null, "a wildcard in the middle is not a prefix");
  assert.equal(codexPrefix("*", "deny"), null);
  const { text, skipped } = codexRules(PERMS);
  assert.match(text, /^# Generated by nexo/);
  assert.match(text, /prefix_rule\(pattern = \["git", "tag"\], decision = "forbidden", justification = "nexo: deny git tag -d\*"\)/);
  assert.match(text, /prefix_rule\(pattern = \["git"\], decision = "prompt"/);
  assert.match(text, /pattern = \["rm"\], decision = "forbidden"/);
  assert.deepEqual(skipped, ['commands allow "git status*"', 'commands allow "npm run test*"']);
});

test("Codex config: approvals from the default (never \"never\"), MCP servers for Codex only, valid TOML values", () => {
  const toml = codexConfig(PERMS, MCP);
  assert.ok(toml.startsWith(CODEX_HEADER));
  assert.match(toml, /approval_policy = "on-request"\nsandbox_mode = "workspace-write"/);
  assert.match(toml, /\[mcp_servers\.notion\]\ncommand = "npx"\nargs = \["-y", "notion-mcp"\]\nenv = \{ TOKEN_REF = "secrets\/notion" \}/);
  assert.doesNotMatch(toml, /remote|claude-only/);
  assert.match(codexConfig({ default: "deny" }, []), /approval_policy = "untrusted"/);
  assert.match(codexConfig({ default: "allow" }, []), /approval_policy = "on-request"/);
});

test("Gemini: allowed commands as run_shell_command(prefix)", () => {
  assert.deepEqual(geminiAllowed(PERMS), ["run_shell_command(git status)", "run_shell_command(npm run test)"]);
  assert.deepEqual(geminiAllowed({}), []);
});

test("unenforced lists each tool's gaps; Claude and OpenCode enforce these rules", () => {
  assert.deepEqual(unenforced("claude", PERMS), []);
  assert.deepEqual(unenforced("opencode", PERMS), []);
  assert.ok(unenforced("opencode", { connections: { n: { write: "ask" } } }).some((g) => /connection decisions/.test(g)));
  const codex = unenforced("codex", PERMS);
  assert.ok(codex.some((g) => /commands allow "npm run test\*"/.test(g)));
  assert.ok(codex.some((g) => /file rules/.test(g)));
  assert.ok(codex.some((g) => /trust the project/.test(g)));
  const gemini = unenforced("gemini", { ...PERMS, commands: { ...PERMS.commands, allow: ["docker * ps"] } });
  assert.ok(gemini.some((g) => /command deny rules/.test(g)));
  assert.ok(gemini.some((g) => /file deny rules/.test(g)));
  assert.ok(gemini.some((g) => /prefix only/.test(g)));
});

test("nexo update writes OpenCode's, Codex's and Gemini's files; a user's own Codex config is kept", async () => {
  const root = await freshEnv("claude,gemini,opencode,codex");
  mkdirSync(join(root, "library", "agents"), { recursive: true });
  writeFileSync(join(root, "library", "agents", "reviewer.md"), "---\nname: reviewer\ndescription: Reviews diffs\nmodel: haiku\n---\nReview it.\n");
  update({ root });
  const opencode = JSON.parse(readFileSync(join(root, "opencode.json"), "utf8"));
  assert.equal(opencode.$schema, "https://opencode.ai/config.json");
  assert.equal(opencode.permission.bash["*"], "ask");
  assert.ok(existsSync(join(root, ".opencode", "skills")), "skills linked");
  assert.match(readFileSync(join(root, ".opencode", "agents", "reviewer.md"), "utf8"), /^---\ndescription: Reviews diffs\nmode: subagent\n---\n/);
  assert.ok(readFileSync(join(root, ".codex", "config.toml"), "utf8").startsWith(CODEX_HEADER));
  assert.match(readFileSync(join(root, ".codex", "rules", "nexo.rules"), "utf8"), /prefix_rule/);
  const gemini = JSON.parse(readFileSync(join(root, ".gemini", "settings.json"), "utf8"));
  assert.equal(gemini.context.fileName, "AGENTS.md");
  assert.ok(Array.isArray(gemini.tools.allowed));
  assert.equal(gemini.contextFileName, undefined, "the v1 key is gone");

  writeFileSync(join(root, ".codex", "config.toml"), 'model = "mine"\n');
  writeFileSync(join(root, ".gemini", "settings.json"), JSON.stringify({ context: { fileName: "X.md", other: 1 }, tools: { exclude: ["a"] }, theme: "dark" }));
  update({ root });
  assert.equal(readFileSync(join(root, ".codex", "config.toml"), "utf8"), 'model = "mine"\n', "a config.toml nexo did not write stays");
  const merged = JSON.parse(readFileSync(join(root, ".gemini", "settings.json"), "utf8"));
  assert.deepEqual([merged.context.other, merged.tools.exclude, merged.theme, merged.context.fileName], [1, ["a"], "dark", "AGENTS.md"], "the user's keys stay");
});

test("onPath finds an AI's command on PATH, with Windows' .cmd form", async () => {
  const { onPath } = await import("../src/core/exec.ts");
  const files = new Set(["/usr/bin/codex", "C:\\npm\\gemini.cmd"]);
  const exists = (p: string) => files.has(p);
  assert.ok(onPath("codex", { PATH: "/opt:/usr/bin/" }, "linux", exists));
  assert.ok(!onPath("gemini", { PATH: "/usr/bin" }, "linux", exists));
  assert.ok(onPath("gemini", { Path: "C:\\x;C:\\npm" }, "win32", exists));
  assert.ok(!onPath("codex", {}, "linux", exists));
});
