// The agent-os documentation: docs/<lang>/<slug>.md with a frontmatter (title, summary, order). English is the
// reference; every language has the same documents with the same sections. Used by scripts/docs-index.ts
// (generates docs/README.md and checks the docs) and by the docs module (the in-app index and reader).
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join, normalize, relative } from "node:path";

export const DOC_LANGUAGES = ["en", "es"] as const;
export type DocLanguage = (typeof DOC_LANGUAGES)[number];

export interface DocMeta {
  slug: string;
  lang: DocLanguage;
  title: string;
  summary: string;
  order: number;
  /** The `## ` headings, in order (the outline both languages must share). */
  sections: string[];
}

export interface Doc extends DocMeta {
  /** The markdown without its frontmatter. */
  body: string;
}

const SLUG = /^[a-z0-9-]+$/;
export const isDocLanguage = (v: unknown): v is DocLanguage => DOC_LANGUAGES.includes(v as DocLanguage);

function parse(text: string): { meta: Record<string, string>; body: string } {
  const m = /^---\n([\s\S]*?)\n---\n?/.exec(text);
  if (!m) return { meta: {}, body: text };
  const meta: Record<string, string> = {};
  for (const line of m[1]!.split("\n")) {
    const i = line.indexOf(":");
    if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return { meta, body: text.slice(m[0].length) };
}

/** One document, or null when the slug or language is unknown. */
export function readDoc(docsDir: string, lang: DocLanguage, slug: string): Doc | null {
  if (!SLUG.test(slug)) return null;
  const file = join(docsDir, lang, `${slug}.md`);
  if (!existsSync(file)) return null;
  const { meta, body } = parse(readFileSync(file, "utf8"));
  return {
    slug,
    lang,
    title: meta.title ?? slug,
    summary: meta.summary ?? "",
    order: Number(meta.order) || 999,
    sections: [...body.matchAll(/^## (.+)$/gm)].map((h) => h[1]!.trim()),
    body,
  };
}

/** The documents of a language, in reading order. */
export function listDocs(docsDir: string, lang: DocLanguage): DocMeta[] {
  const dir = join(docsDir, lang);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => readDoc(docsDir, lang, f.slice(0, -3)))
    .filter((d): d is Doc => !!d)
    .map(({ body: _body, ...meta }) => meta)
    .sort((a, b) => a.order - b.order || a.slug.localeCompare(b.slug));
}

/** What is wrong with the docs: a missing translation or frontmatter field, a different outline, a broken link. */
export function checkDocs(docsDir: string): string[] {
  const problems: string[] = [];
  const reference = listDocs(docsDir, "en");
  for (const lang of DOC_LANGUAGES) {
    for (const meta of listDocs(docsDir, lang)) {
      const file = `docs/${lang}/${meta.slug}.md`;
      const doc = readDoc(docsDir, lang, meta.slug)!;
      const raw = readFileSync(join(docsDir, lang, `${meta.slug}.md`), "utf8");
      for (const field of ["title", "summary", "order"]) if (!new RegExp(`^${field}:`, "m").test(raw.split("\n---")[0] ?? "")) problems.push(`${file}: frontmatter has no ${field}`);
      if (lang !== "en") {
        const en = reference.find((d) => d.slug === meta.slug);
        if (!en) problems.push(`${file}: no English original (docs/en/${meta.slug}.md)`);
        else {
          if (en.sections.length !== meta.sections.length) problems.push(`${file}: ${meta.sections.length} sections, the English one has ${en.sections.length}`);
          if (en.order !== meta.order) problems.push(`${file}: order ${meta.order}, the English one has ${en.order}`);
        }
      }
      // Relative links must point to something that exists (other docs, or files of the package).
      for (const link of doc.body.matchAll(/\]\((?!https?:|#|mailto:)([^)\s#]+)(?:#[^)]*)?\)/g)) {
        const target = normalize(join(docsDir, lang, link[1]!));
        if (!existsSync(target)) problems.push(`${file}: broken link ${link[1]} (${relative(dirname(docsDir), target)})`);
      }
    }
  }
  for (const lang of DOC_LANGUAGES.filter((l) => l !== "en")) {
    for (const en of reference) {
      if (!existsSync(join(docsDir, lang, `${en.slug}.md`))) problems.push(`docs/${lang}/${en.slug}.md is missing (translation of docs/en/${en.slug}.md)`);
    }
  }
  return problems;
}

const HEADINGS: Record<DocLanguage, { title: string; doc: string; about: string }> = {
  en: { title: "English", doc: "Document", about: "What it covers" },
  es: { title: "Español", doc: "Documento", about: "Qué cubre" },
};

/** docs/README.md: the index of every language, generated from the documents themselves. */
export function renderIndex(docsDir: string): string {
  const out = [
    "<!-- Generated by scripts/docs-index.ts from each document's frontmatter. Do not edit by hand: run `npm run docs`. -->",
    "",
    "# agent-os documentation · documentación",
    "",
    "Every document exists in English and Spanish; the app shows them in its own language (the Docs view).",
    "Cada documento existe en inglés y en español; la app los muestra en su idioma (la vista Docs).",
  ];
  for (const lang of DOC_LANGUAGES) {
    const h = HEADINGS[lang];
    out.push("", `## ${h.title}`, "", `| ${h.doc} | ${h.about} |`, "|---|---|");
    for (const d of listDocs(docsDir, lang)) out.push(`| [${d.title}](${lang}/${d.slug}.md) | ${d.summary} |`);
  }
  return `${out.join("\n")}\n`;
}
